// Package metrics provides Prometheus metrics for the reporter service.
package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// ReportsGeneratedTotal counts total reports generated by type.
	ReportsGeneratedTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "reporter_reports_generated_total",
		Help: "Total reports generated",
	}, []string{"report_type"})

	// ReportGenerationDuration tracks report generation latency.
	ReportGenerationDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "reporter_report_generation_duration_seconds",
		Help:    "Time spent generating a report",
		Buckets: []float64{0.1, 0.5, 1, 2.5, 5, 10, 30, 60},
	}, []string{"report_type"})

	// ReportErrorsTotal counts report generation errors.
	ReportErrorsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "reporter_report_errors_total",
		Help: "Total report generation errors",
	}, []string{"report_type", "error_type"})

	// HTTPRequestsTotal counts total HTTP requests by method, path, and status code.
	HTTPRequestsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "reporter_http_requests_total",
		Help: "Total HTTP requests handled by the reporter service",
	}, []string{"method", "path", "status"})

	// HTTPRequestDuration tracks HTTP request processing latency.
	HTTPRequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "reporter_http_request_duration_seconds",
		Help:    "HTTP request processing latency",
		Buckets: prometheus.DefBuckets,
	}, []string{"method", "path"})
)
